### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Diaglyonok** [PonnamKarthik/FlutterWebView#2]
![image](https://user-images.githubusercontent.com/18545029/46018106-cb8d2680-c0e1-11e8-997e-0951c1e559d4.png)
and as text:
(
C:\Work\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_native_web-0.1.2\android\src\main\java\io\github\ponnamkarthik\flutterwebview\FlutterwebviewFactory.java:10: error: no interface expected here
public class FlutterwebviewFactory extends PlatformViewFactory {
                                           ^
C:\Work\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_native_web-0.1.2\android\src\main\java\io\github\ponnamkarthik\flutterwebview\FlutterwebviewFactory.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\Work\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_native_web-0.1.2\android\src\main\java\io\github\ponnamkarthik\flutterwebview\FlutterwebviewPlugin.java:11: error: incompatible types: FlutterwebviewFactory cannot be converted to PlatformViewFactory
                    "ponnamkarthik/flutterwebview", new FlutterwebviewFactory(registrar));
                                                    ^
Note: C:\Work\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_native_web-0.1.2\android\src\main\java\io\github\ponnamkarthik\flutterwebview\FlutterWeb.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_native_web:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Finished with error: Gradle build failed: 1
)

Getting this when install this lib.

Is there any solutions?

**Comment by Diaglyonok** [comment]
Flutter doctor:

![image](https://user-images.githubusercontent.com/18545029/46018603-ef04a100-c0e2-11e8-927b-d11b1fd8e96d.png)

**Comment by Diaglyonok** [comment]
Changing code of FLutterWebViewFactory in android/src/main/java/io/github/ponnamkarthik/flutterwebview/FlutterwebviewFactory.java to

`package io.github.ponnamkarthik.flutterwebview;

import android.content.Context;
import io.flutter.plugin.common.StandardMessageCodec;
import io.flutter.plugin.platform.PlatformView;
import io.flutter.plugin.platform.PlatformViewFactory;

import static io.flutter.plugin.common.PluginRegistry.Registrar;

public class FlutterwebviewFactory implements PlatformViewFactory {

    private final Registrar mPluginRegistrar;

    public FlutterwebviewFactory(Registrar registrar) {
        super();
        mPluginRegistrar = registrar;
    }

    @Override
    public PlatformView create(Context context, int i) {
        return new FlutterWeb(context, mPluginRegistrar, i);
    }

}`

solves the problem

**Comment by PonnamKarthik** [comment]
fixed `1.0.2`

**Comment by rajendrachauhan** [comment]
github/ponnamkarthik/flutterwebview/FlutterwebviewFactory.java:15: error: constructor PlatformViewFactory in class PlatformViewFactory cannot be applied to given types;
        super();
        ^
  required: MessageCodec<Object>
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: /media/shreejiweb/ssdsoftware/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_web-1.0.2/android/src/main/java/io/github/ponnamkarthik/flutterwebview/FlutterWeb.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

Is there any solution ?

**Comment by Muchene** [comment]
I think the original code was correct, and the patch may have caused some problems
Changing that line back to 
``super(StandardMessageCodec.INSTANCE);``  

fixed my compilation issue. 

Thanks so much for the package!!

**Comment by maddesa** [comment]
I see the same thing as @Muchene 
Making the change has fixed the issue.
