### ISSUE TITLE
 Garbled characters appear on some android devices

### ISSUE THREAD

**Issue by gejw0623** [PonnamKarthik/FlutterWebView#9]
Hi，we found the garbled characters appear on some android devices

so, i'm change the code to use
`
webView.loadDataWithBaseURL(null, html, "text/html", "utf-8",null);
`
to repleace this
`
webView.loadData(html, "text/html", "utf-8");
`
![image](https://user-images.githubusercontent.com/4335738/51441238-774e2800-1d0a-11e9-8b78-d9e9181635d7.png)

**Comment by PonnamKarthik** [comment]
Thanks @gejw0623 will replace in new version

**Comment by PonnamKarthik** [comment]
fixed `1.0.2`
